import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import type { GeneratedFile } from "@/lib/types";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { files, projectName = "autoforgeai-project" }: {
      files: GeneratedFile[];
      projectName?: string;
    } = body;

    if (!files || files.length === 0) {
      return NextResponse.json({ error: "No files to download" }, { status: 400 });
    }

    // Create ZIP
    const zip = new JSZip();
    const folder = zip.folder(projectName);

    if (!folder) {
      return NextResponse.json({ error: "Failed to create ZIP folder" }, { status: 500 });
    }

    for (const file of files) {
      folder.file(file.path, file.content);
    }

    // Add a helpful root-level README
    folder.file("AUTOFORGEAI_README.md", `# ${projectName}

Generated by AutoForgeAI powered by AWS Amazon Nova

## Getting Started

\`\`\`bash
cd ${projectName}
npm install
cp .env.example .env.local
# Fill in your environment variables in .env.local
npm run dev
\`\`\`

## Files Generated

${files.map((f) => `- \`${f.path}\``).join("\n")}

---
*Generated at ${new Date().toISOString()} by AutoForgeAI*
`);

    const zipBuffer = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    const uint8 = new Uint8Array(zipBuffer);
    return new NextResponse(uint8, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${projectName}.zip"`,
        "Content-Length": uint8.length.toString(),
      },
    });
  } catch (error) {
    console.error("[Download] Error creating ZIP:", error);
    return NextResponse.json(
      { error: "Failed to create download archive" },
      { status: 500 }
    );
  }
}
